#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym__wc = 1,
  anon_sym_LPAREN = 2,
  aux_sym__comment_contents_token1 = 3,
  anon_sym_RPAREN = 4,
  anon_sym_POUND = 5,
  sym__first = 6,
  sym__digit = 7,
  anon_sym_DOT = 8,
  anon_sym_DQUOTE = 9,
  anon_sym_SQUOTE = 10,
  anon_sym_BSLASH = 11,
  anon_sym_DASH = 12,
  aux_sym_str_token1 = 13,
  aux_sym_str_token2 = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym_source_file = 17,
  sym__sp = 18,
  sym__comment_contents = 19,
  sym_comment = 20,
  sym__int = 21,
  sym__float = 22,
  sym_escape_char = 23,
  sym_sym = 24,
  sym_num = 25,
  sym_str = 26,
  sym__atom = 27,
  sym__expression = 28,
  sym_tag = 29,
  sym_cell = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym__sp_repeat1 = 32,
  aux_sym__comment_contents_repeat1 = 33,
  aux_sym__int_repeat1 = 34,
  aux_sym_sym_repeat1 = 35,
  aux_sym_str_repeat1 = 36,
  aux_sym_str_repeat2 = 37,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__wc] = "_wc",
  [anon_sym_LPAREN] = "(",
  [aux_sym__comment_contents_token1] = "_comment_contents_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_POUND] = "#",
  [sym__first] = "_first",
  [sym__digit] = "_digit",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DASH] = "-",
  [aux_sym_str_token1] = "str_token1",
  [aux_sym_str_token2] = "str_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__sp] = "_sp",
  [sym__comment_contents] = "_comment_contents",
  [sym_comment] = "comment",
  [sym__int] = "_int",
  [sym__float] = "_float",
  [sym_escape_char] = "escape_char",
  [sym_sym] = "sym",
  [sym_num] = "num",
  [sym_str] = "str",
  [sym__atom] = "_atom",
  [sym__expression] = "_expression",
  [sym_tag] = "tag",
  [sym_cell] = "cell",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__sp_repeat1] = "_sp_repeat1",
  [aux_sym__comment_contents_repeat1] = "_comment_contents_repeat1",
  [aux_sym__int_repeat1] = "_int_repeat1",
  [aux_sym_sym_repeat1] = "sym_repeat1",
  [aux_sym_str_repeat1] = "str_repeat1",
  [aux_sym_str_repeat2] = "str_repeat2",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__wc] = sym__wc,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym__comment_contents_token1] = aux_sym__comment_contents_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym__first] = sym__first,
  [sym__digit] = sym__digit,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_str_token1] = aux_sym_str_token1,
  [aux_sym_str_token2] = aux_sym_str_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__sp] = sym__sp,
  [sym__comment_contents] = sym__comment_contents,
  [sym_comment] = sym_comment,
  [sym__int] = sym__int,
  [sym__float] = sym__float,
  [sym_escape_char] = sym_escape_char,
  [sym_sym] = sym_sym,
  [sym_num] = sym_num,
  [sym_str] = sym_str,
  [sym__atom] = sym__atom,
  [sym__expression] = sym__expression,
  [sym_tag] = sym_tag,
  [sym_cell] = sym_cell,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__sp_repeat1] = aux_sym__sp_repeat1,
  [aux_sym__comment_contents_repeat1] = aux_sym__comment_contents_repeat1,
  [aux_sym__int_repeat1] = aux_sym__int_repeat1,
  [aux_sym_sym_repeat1] = aux_sym_sym_repeat1,
  [aux_sym_str_repeat1] = aux_sym_str_repeat1,
  [aux_sym_str_repeat2] = aux_sym_str_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__wc] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__comment_contents_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym__first] = {
    .visible = false,
    .named = true,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_str_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sp] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_contents] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sp_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_contents_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__int_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sym_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 6:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 7:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == '=' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__wc);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__comment_contents_token1);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__comment_contents_token1);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__first);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__digit);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_str_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_str_token1);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_str_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_str_token2);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 9},
  [80] = {.lex_state = 9},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 6},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 6},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 5},
  [102] = {.lex_state = 6},
  [103] = {.lex_state = 6},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 6},
  [108] = {.lex_state = 6},
  [109] = {.lex_state = 6},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 6},
  [113] = {.lex_state = 6},
  [114] = {.lex_state = 6},
  [115] = {.lex_state = 6},
  [116] = {.lex_state = 6},
  [117] = {.lex_state = 5},
  [118] = {.lex_state = 6},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym__first] = ACTIONS(1),
    [sym__digit] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(125),
    [sym__sp] = STATE(11),
    [sym_comment] = STATE(27),
    [sym__int] = STATE(107),
    [sym__float] = STATE(107),
    [sym_sym] = STATE(53),
    [sym_num] = STATE(53),
    [sym_str] = STATE(53),
    [sym__atom] = STATE(53),
    [sym__expression] = STATE(53),
    [sym_cell] = STATE(53),
    [aux_sym__sp_repeat1] = STATE(27),
    [aux_sym__int_repeat1] = STATE(74),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__wc] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [sym__first] = ACTIONS(11),
    [sym__digit] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
  },
  [2] = {
    [sym__sp] = STATE(17),
    [sym_comment] = STATE(24),
    [sym__int] = STATE(102),
    [sym__float] = STATE(102),
    [sym_sym] = STATE(37),
    [sym_num] = STATE(37),
    [sym_str] = STATE(37),
    [sym__atom] = STATE(37),
    [sym__expression] = STATE(37),
    [sym_tag] = STATE(5),
    [sym_cell] = STATE(37),
    [aux_sym__sp_repeat1] = STATE(24),
    [aux_sym__int_repeat1] = STATE(72),
    [sym__wc] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(29),
    [sym__first] = ACTIONS(31),
    [sym__digit] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(43),
  },
  [3] = {
    [sym__sp] = STATE(10),
    [sym_comment] = STATE(24),
    [sym__int] = STATE(102),
    [sym__float] = STATE(102),
    [sym_sym] = STATE(58),
    [sym_num] = STATE(58),
    [sym_str] = STATE(58),
    [sym__atom] = STATE(58),
    [sym__expression] = STATE(58),
    [sym_tag] = STATE(4),
    [sym_cell] = STATE(58),
    [aux_sym__sp_repeat1] = STATE(24),
    [aux_sym__int_repeat1] = STATE(72),
    [sym__wc] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_POUND] = ACTIONS(29),
    [sym__first] = ACTIONS(31),
    [sym__digit] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(43),
  },
  [4] = {
    [sym__sp] = STATE(8),
    [sym_comment] = STATE(24),
    [sym__int] = STATE(102),
    [sym__float] = STATE(102),
    [sym_sym] = STATE(36),
    [sym_num] = STATE(36),
    [sym_str] = STATE(36),
    [sym__atom] = STATE(36),
    [sym__expression] = STATE(36),
    [sym_cell] = STATE(36),
    [aux_sym__sp_repeat1] = STATE(24),
    [aux_sym__int_repeat1] = STATE(72),
    [sym__wc] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_POUND] = ACTIONS(29),
    [sym__first] = ACTIONS(31),
    [sym__digit] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(41),
  },
  [5] = {
    [sym__sp] = STATE(12),
    [sym_comment] = STATE(24),
    [sym__int] = STATE(102),
    [sym__float] = STATE(102),
    [sym_sym] = STATE(47),
    [sym_num] = STATE(47),
    [sym_str] = STATE(47),
    [sym__atom] = STATE(47),
    [sym__expression] = STATE(47),
    [sym_cell] = STATE(47),
    [aux_sym__sp_repeat1] = STATE(24),
    [aux_sym__int_repeat1] = STATE(72),
    [sym__wc] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_POUND] = ACTIONS(29),
    [sym__first] = ACTIONS(31),
    [sym__digit] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(41),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [40] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [80] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(43), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [120] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [160] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(36), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [200] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      sym__digit,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_DASH,
    STATE(74), 1,
      aux_sym__int_repeat1,
    STATE(107), 2,
      sym__int,
      sym__float,
    STATE(41), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [240] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(60), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [280] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [320] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [360] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [400] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      sym__digit,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      aux_sym__int_repeat1,
    STATE(107), 2,
      sym__int,
      sym__float,
    STATE(116), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [440] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(47), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [480] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [520] = 11,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [560] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      sym__digit,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_DASH,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      aux_sym__int_repeat1,
    STATE(107), 2,
      sym__int,
      sym__float,
    STATE(116), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [600] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      sym__digit,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      aux_sym__int_repeat1,
    STATE(107), 2,
      sym__int,
      sym__float,
    STATE(116), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [640] = 10,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      sym__digit,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_DASH,
    STATE(74), 1,
      aux_sym__int_repeat1,
    STATE(107), 2,
      sym__int,
      sym__float,
    STATE(116), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [677] = 10,
    ACTIONS(31), 1,
      sym__first,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DASH,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(102), 2,
      sym__int,
      sym__float,
    STATE(109), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [714] = 4,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(103), 1,
      sym__wc,
    STATE(26), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(105), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [735] = 5,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 1,
      sym__wc,
    ACTIONS(114), 1,
      anon_sym_POUND,
    STATE(25), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(112), 7,
      anon_sym_LPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [758] = 4,
    ACTIONS(117), 1,
      sym__wc,
    ACTIONS(120), 1,
      anon_sym_POUND,
    STATE(26), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(112), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [779] = 5,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      sym__wc,
    STATE(25), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(105), 7,
      anon_sym_LPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [802] = 2,
    ACTIONS(127), 1,
      sym__wc,
    ACTIONS(129), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [817] = 2,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(133), 8,
      anon_sym_LPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [832] = 2,
    ACTIONS(135), 1,
      sym__wc,
    ACTIONS(137), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [847] = 2,
    ACTIONS(131), 1,
      sym__wc,
    ACTIONS(133), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [862] = 2,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(141), 8,
      anon_sym_LPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [877] = 2,
    ACTIONS(139), 1,
      sym__wc,
    ACTIONS(141), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [892] = 2,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(129), 8,
      anon_sym_LPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_DASH,
  [907] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [927] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym__sp,
    STATE(45), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [947] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    STATE(15), 1,
      sym__sp,
    STATE(48), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [967] = 3,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 2,
      sym__wc,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token2,
  [981] = 3,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 2,
      sym__wc,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token2,
  [995] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1015] = 6,
    ACTIONS(5), 1,
      sym__wc,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym__sp,
    STATE(54), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1035] = 6,
    ACTIONS(5), 1,
      sym__wc,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym__sp,
    STATE(56), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1055] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym__sp,
    STATE(40), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1075] = 6,
    ACTIONS(161), 1,
      sym__wc,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(166), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1095] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1115] = 2,
    ACTIONS(155), 3,
      sym__wc,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token1,
  [1127] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym__sp,
    STATE(59), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1147] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1167] = 2,
    ACTIONS(149), 3,
      sym__wc,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token1,
  [1179] = 2,
    ACTIONS(155), 3,
      sym__wc,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token2,
  [1191] = 3,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 2,
      sym__wc,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token1,
  [1205] = 2,
    ACTIONS(149), 3,
      sym__wc,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token2,
  [1217] = 6,
    ACTIONS(5), 1,
      sym__wc,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym__sp,
    STATE(42), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1237] = 6,
    ACTIONS(5), 1,
      sym__wc,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      sym__sp,
    STATE(56), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1257] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1277] = 6,
    ACTIONS(161), 1,
      sym__wc,
    ACTIONS(166), 1,
      anon_sym_POUND,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym__sp,
    STATE(56), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1297] = 3,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 2,
      sym__wc,
      anon_sym_POUND,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token1,
  [1311] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym__sp,
    STATE(55), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1331] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      sym__sp,
    STATE(44), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1351] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(29), 1,
      anon_sym_POUND,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      sym__sp,
    STATE(35), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1371] = 4,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      aux_sym_str_token2,
    ACTIONS(175), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
    STATE(66), 2,
      sym_escape_char,
      aux_sym_str_repeat2,
  [1386] = 4,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      aux_sym_str_token1,
    ACTIONS(183), 2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
    STATE(68), 2,
      sym_escape_char,
      aux_sym_str_repeat1,
  [1401] = 4,
    ACTIONS(187), 1,
      sym__wc,
    ACTIONS(191), 1,
      sym__digit,
    STATE(63), 1,
      aux_sym__int_repeat1,
    ACTIONS(189), 3,
      anon_sym_RPAREN,
      anon_sym_POUND,
      anon_sym_DOT,
  [1416] = 4,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      aux_sym_str_token2,
    ACTIONS(175), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
    STATE(61), 2,
      sym_escape_char,
      aux_sym_str_repeat2,
  [1431] = 4,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    ACTIONS(200), 1,
      aux_sym_str_token1,
    ACTIONS(183), 2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
    STATE(62), 2,
      sym_escape_char,
      aux_sym_str_repeat1,
  [1446] = 3,
    ACTIONS(205), 1,
      aux_sym_str_token2,
    STATE(66), 2,
      sym_escape_char,
      aux_sym_str_repeat2,
    ACTIONS(202), 3,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
  [1459] = 4,
    ACTIONS(208), 1,
      sym__wc,
    STATE(75), 1,
      aux_sym_sym_repeat1,
    ACTIONS(210), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(212), 2,
      sym__first,
      sym__digit,
  [1474] = 3,
    ACTIONS(217), 1,
      aux_sym_str_token1,
    STATE(68), 2,
      sym_escape_char,
      aux_sym_str_repeat1,
    ACTIONS(214), 3,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
  [1487] = 4,
    ACTIONS(222), 1,
      anon_sym_POUND,
    STATE(69), 1,
      aux_sym_sym_repeat1,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(224), 2,
      sym__first,
      sym__digit,
  [1502] = 4,
    ACTIONS(227), 1,
      anon_sym_SQUOTE,
    ACTIONS(229), 1,
      aux_sym_str_token2,
    ACTIONS(175), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
    STATE(77), 2,
      sym_escape_char,
      aux_sym_str_repeat2,
  [1517] = 4,
    ACTIONS(233), 1,
      anon_sym_POUND,
    STATE(69), 1,
      aux_sym_sym_repeat1,
    ACTIONS(231), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(235), 2,
      sym__first,
      sym__digit,
  [1532] = 5,
    ACTIONS(237), 1,
      sym__wc,
    ACTIONS(241), 1,
      sym__digit,
    ACTIONS(243), 1,
      anon_sym_DOT,
    STATE(63), 1,
      aux_sym__int_repeat1,
    ACTIONS(239), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1549] = 4,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      aux_sym_str_token1,
    ACTIONS(183), 2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
    STATE(78), 2,
      sym_escape_char,
      aux_sym_str_repeat1,
  [1564] = 5,
    ACTIONS(239), 1,
      anon_sym_POUND,
    ACTIONS(249), 1,
      sym__digit,
    ACTIONS(251), 1,
      anon_sym_DOT,
    STATE(76), 1,
      aux_sym__int_repeat1,
    ACTIONS(237), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1581] = 4,
    ACTIONS(231), 1,
      sym__wc,
    STATE(79), 1,
      aux_sym_sym_repeat1,
    ACTIONS(233), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(253), 2,
      sym__first,
      sym__digit,
  [1596] = 4,
    ACTIONS(255), 1,
      sym__digit,
    STATE(76), 1,
      aux_sym__int_repeat1,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(189), 2,
      anon_sym_POUND,
      anon_sym_DOT,
  [1611] = 4,
    ACTIONS(179), 1,
      aux_sym_str_token2,
    ACTIONS(258), 1,
      anon_sym_SQUOTE,
    ACTIONS(175), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
    STATE(66), 2,
      sym_escape_char,
      aux_sym_str_repeat2,
  [1626] = 4,
    ACTIONS(185), 1,
      aux_sym_str_token1,
    ACTIONS(260), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 2,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
    STATE(68), 2,
      sym_escape_char,
      aux_sym_str_repeat1,
  [1641] = 4,
    ACTIONS(220), 1,
      sym__wc,
    STATE(79), 1,
      aux_sym_sym_repeat1,
    ACTIONS(222), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(262), 2,
      sym__first,
      sym__digit,
  [1656] = 4,
    ACTIONS(210), 1,
      anon_sym_POUND,
    STATE(71), 1,
      aux_sym_sym_repeat1,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(265), 2,
      sym__first,
      sym__digit,
  [1671] = 4,
    ACTIONS(249), 1,
      sym__digit,
    ACTIONS(269), 1,
      anon_sym_POUND,
    STATE(76), 1,
      aux_sym__int_repeat1,
    ACTIONS(267), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1685] = 4,
    ACTIONS(55), 1,
      sym__digit,
    ACTIONS(57), 1,
      anon_sym_DOT,
    STATE(72), 1,
      aux_sym__int_repeat1,
    STATE(103), 2,
      sym__int,
      sym__float,
  [1699] = 4,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    STATE(92), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1713] = 4,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(277), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(83), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1727] = 4,
    ACTIONS(283), 1,
      anon_sym_POUND,
    ACTIONS(285), 1,
      sym__digit,
    STATE(81), 1,
      aux_sym__int_repeat1,
    ACTIONS(281), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1741] = 4,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(92), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1755] = 4,
    ACTIONS(241), 1,
      sym__digit,
    ACTIONS(267), 1,
      sym__wc,
    STATE(63), 1,
      aux_sym__int_repeat1,
    ACTIONS(269), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1769] = 4,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
    STATE(92), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1783] = 4,
    ACTIONS(281), 1,
      sym__wc,
    ACTIONS(291), 1,
      sym__digit,
    STATE(87), 1,
      aux_sym__int_repeat1,
    ACTIONS(283), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1797] = 4,
    ACTIONS(241), 1,
      sym__digit,
    ACTIONS(281), 1,
      sym__wc,
    STATE(63), 1,
      aux_sym__int_repeat1,
    ACTIONS(283), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1811] = 4,
    ACTIONS(75), 1,
      sym__digit,
    ACTIONS(77), 1,
      anon_sym_DOT,
    STATE(74), 1,
      aux_sym__int_repeat1,
    STATE(104), 2,
      sym__int,
      sym__float,
  [1825] = 4,
    ACTIONS(293), 1,
      anon_sym_LPAREN,
    ACTIONS(296), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
    STATE(92), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1839] = 4,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(301), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(88), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1853] = 4,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(305), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(86), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1867] = 4,
    ACTIONS(249), 1,
      sym__digit,
    ACTIONS(283), 1,
      anon_sym_POUND,
    STATE(76), 1,
      aux_sym__int_repeat1,
    ACTIONS(281), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1881] = 1,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token1,
  [1888] = 1,
    ACTIONS(151), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      aux_sym_str_token2,
  [1895] = 2,
    ACTIONS(311), 1,
      anon_sym_POUND,
    ACTIONS(309), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1903] = 2,
    ACTIONS(315), 1,
      anon_sym_POUND,
    ACTIONS(313), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1911] = 2,
    ACTIONS(313), 1,
      sym__wc,
    ACTIONS(315), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1919] = 1,
    ACTIONS(129), 3,
      anon_sym_LPAREN,
      aux_sym__comment_contents_token1,
      anon_sym_RPAREN,
  [1925] = 2,
    ACTIONS(317), 1,
      sym__wc,
    ACTIONS(319), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1933] = 2,
    ACTIONS(321), 1,
      sym__wc,
    ACTIONS(323), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1941] = 2,
    ACTIONS(323), 1,
      anon_sym_POUND,
    ACTIONS(321), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1949] = 2,
    ACTIONS(327), 1,
      anon_sym_POUND,
    ACTIONS(325), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1957] = 2,
    ACTIONS(329), 1,
      sym__wc,
    ACTIONS(331), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1965] = 2,
    ACTIONS(319), 1,
      anon_sym_POUND,
    ACTIONS(317), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1973] = 2,
    ACTIONS(335), 1,
      anon_sym_POUND,
    ACTIONS(333), 2,
      ts_builtin_sym_end,
      sym__wc,
  [1981] = 2,
    ACTIONS(171), 1,
      sym__wc,
    ACTIONS(164), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1989] = 3,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    ACTIONS(337), 1,
      sym__digit,
    STATE(110), 1,
      aux_sym__int_repeat1,
  [1999] = 3,
    ACTIONS(340), 1,
      sym__digit,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym__int_repeat1,
  [2009] = 2,
    ACTIONS(346), 1,
      anon_sym_POUND,
    ACTIONS(344), 2,
      ts_builtin_sym_end,
      sym__wc,
  [2017] = 2,
    ACTIONS(325), 1,
      sym__wc,
    ACTIONS(327), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [2025] = 2,
    ACTIONS(333), 1,
      sym__wc,
    ACTIONS(335), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [2033] = 2,
    ACTIONS(344), 1,
      sym__wc,
    ACTIONS(346), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [2041] = 2,
    ACTIONS(164), 1,
      anon_sym_POUND,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      sym__wc,
  [2049] = 1,
    ACTIONS(133), 3,
      anon_sym_LPAREN,
      aux_sym__comment_contents_token1,
      anon_sym_RPAREN,
  [2055] = 2,
    ACTIONS(309), 1,
      sym__wc,
    ACTIONS(311), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [2063] = 2,
    ACTIONS(331), 1,
      anon_sym_POUND,
    ACTIONS(329), 2,
      ts_builtin_sym_end,
      sym__wc,
  [2071] = 2,
    ACTIONS(348), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym__comment_contents,
  [2078] = 2,
    ACTIONS(350), 1,
      sym__digit,
    STATE(95), 1,
      aux_sym__int_repeat1,
  [2085] = 2,
    ACTIONS(352), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym__comment_contents,
  [2092] = 2,
    ACTIONS(354), 1,
      sym__digit,
    STATE(90), 1,
      aux_sym__int_repeat1,
  [2099] = 2,
    ACTIONS(356), 1,
      sym__digit,
    STATE(111), 1,
      aux_sym__int_repeat1,
  [2106] = 1,
    ACTIONS(358), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 40,
  [SMALL_STATE(8)] = 80,
  [SMALL_STATE(9)] = 120,
  [SMALL_STATE(10)] = 160,
  [SMALL_STATE(11)] = 200,
  [SMALL_STATE(12)] = 240,
  [SMALL_STATE(13)] = 280,
  [SMALL_STATE(14)] = 320,
  [SMALL_STATE(15)] = 360,
  [SMALL_STATE(16)] = 400,
  [SMALL_STATE(17)] = 440,
  [SMALL_STATE(18)] = 480,
  [SMALL_STATE(19)] = 520,
  [SMALL_STATE(20)] = 560,
  [SMALL_STATE(21)] = 600,
  [SMALL_STATE(22)] = 640,
  [SMALL_STATE(23)] = 677,
  [SMALL_STATE(24)] = 714,
  [SMALL_STATE(25)] = 735,
  [SMALL_STATE(26)] = 758,
  [SMALL_STATE(27)] = 779,
  [SMALL_STATE(28)] = 802,
  [SMALL_STATE(29)] = 817,
  [SMALL_STATE(30)] = 832,
  [SMALL_STATE(31)] = 847,
  [SMALL_STATE(32)] = 862,
  [SMALL_STATE(33)] = 877,
  [SMALL_STATE(34)] = 892,
  [SMALL_STATE(35)] = 907,
  [SMALL_STATE(36)] = 927,
  [SMALL_STATE(37)] = 947,
  [SMALL_STATE(38)] = 967,
  [SMALL_STATE(39)] = 981,
  [SMALL_STATE(40)] = 995,
  [SMALL_STATE(41)] = 1015,
  [SMALL_STATE(42)] = 1035,
  [SMALL_STATE(43)] = 1055,
  [SMALL_STATE(44)] = 1075,
  [SMALL_STATE(45)] = 1095,
  [SMALL_STATE(46)] = 1115,
  [SMALL_STATE(47)] = 1127,
  [SMALL_STATE(48)] = 1147,
  [SMALL_STATE(49)] = 1167,
  [SMALL_STATE(50)] = 1179,
  [SMALL_STATE(51)] = 1191,
  [SMALL_STATE(52)] = 1205,
  [SMALL_STATE(53)] = 1217,
  [SMALL_STATE(54)] = 1237,
  [SMALL_STATE(55)] = 1257,
  [SMALL_STATE(56)] = 1277,
  [SMALL_STATE(57)] = 1297,
  [SMALL_STATE(58)] = 1311,
  [SMALL_STATE(59)] = 1331,
  [SMALL_STATE(60)] = 1351,
  [SMALL_STATE(61)] = 1371,
  [SMALL_STATE(62)] = 1386,
  [SMALL_STATE(63)] = 1401,
  [SMALL_STATE(64)] = 1416,
  [SMALL_STATE(65)] = 1431,
  [SMALL_STATE(66)] = 1446,
  [SMALL_STATE(67)] = 1459,
  [SMALL_STATE(68)] = 1474,
  [SMALL_STATE(69)] = 1487,
  [SMALL_STATE(70)] = 1502,
  [SMALL_STATE(71)] = 1517,
  [SMALL_STATE(72)] = 1532,
  [SMALL_STATE(73)] = 1549,
  [SMALL_STATE(74)] = 1564,
  [SMALL_STATE(75)] = 1581,
  [SMALL_STATE(76)] = 1596,
  [SMALL_STATE(77)] = 1611,
  [SMALL_STATE(78)] = 1626,
  [SMALL_STATE(79)] = 1641,
  [SMALL_STATE(80)] = 1656,
  [SMALL_STATE(81)] = 1671,
  [SMALL_STATE(82)] = 1685,
  [SMALL_STATE(83)] = 1699,
  [SMALL_STATE(84)] = 1713,
  [SMALL_STATE(85)] = 1727,
  [SMALL_STATE(86)] = 1741,
  [SMALL_STATE(87)] = 1755,
  [SMALL_STATE(88)] = 1769,
  [SMALL_STATE(89)] = 1783,
  [SMALL_STATE(90)] = 1797,
  [SMALL_STATE(91)] = 1811,
  [SMALL_STATE(92)] = 1825,
  [SMALL_STATE(93)] = 1839,
  [SMALL_STATE(94)] = 1853,
  [SMALL_STATE(95)] = 1867,
  [SMALL_STATE(96)] = 1881,
  [SMALL_STATE(97)] = 1888,
  [SMALL_STATE(98)] = 1895,
  [SMALL_STATE(99)] = 1903,
  [SMALL_STATE(100)] = 1911,
  [SMALL_STATE(101)] = 1919,
  [SMALL_STATE(102)] = 1925,
  [SMALL_STATE(103)] = 1933,
  [SMALL_STATE(104)] = 1941,
  [SMALL_STATE(105)] = 1949,
  [SMALL_STATE(106)] = 1957,
  [SMALL_STATE(107)] = 1965,
  [SMALL_STATE(108)] = 1973,
  [SMALL_STATE(109)] = 1981,
  [SMALL_STATE(110)] = 1989,
  [SMALL_STATE(111)] = 1999,
  [SMALL_STATE(112)] = 2009,
  [SMALL_STATE(113)] = 2017,
  [SMALL_STATE(114)] = 2025,
  [SMALL_STATE(115)] = 2033,
  [SMALL_STATE(116)] = 2041,
  [SMALL_STATE(117)] = 2049,
  [SMALL_STATE(118)] = 2055,
  [SMALL_STATE(119)] = 2063,
  [SMALL_STATE(120)] = 2071,
  [SMALL_STATE(121)] = 2078,
  [SMALL_STATE(122)] = 2085,
  [SMALL_STATE(123)] = 2092,
  [SMALL_STATE(124)] = 2099,
  [SMALL_STATE(125)] = 2106,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 0),
  [5] = {.count = 1, .reusable = true}, SHIFT(27),
  [7] = {.count = 1, .reusable = false}, SHIFT(2),
  [9] = {.count = 1, .reusable = false}, SHIFT(120),
  [11] = {.count = 1, .reusable = false}, SHIFT(80),
  [13] = {.count = 1, .reusable = false}, SHIFT(74),
  [15] = {.count = 1, .reusable = false}, SHIFT(121),
  [17] = {.count = 1, .reusable = false}, SHIFT(73),
  [19] = {.count = 1, .reusable = false}, SHIFT(70),
  [21] = {.count = 1, .reusable = false}, SHIFT(91),
  [23] = {.count = 1, .reusable = true}, SHIFT(24),
  [25] = {.count = 1, .reusable = false}, SHIFT(3),
  [27] = {.count = 1, .reusable = false}, SHIFT(99),
  [29] = {.count = 1, .reusable = false}, SHIFT(122),
  [31] = {.count = 1, .reusable = false}, SHIFT(67),
  [33] = {.count = 1, .reusable = false}, SHIFT(72),
  [35] = {.count = 1, .reusable = false}, SHIFT(123),
  [37] = {.count = 1, .reusable = false}, SHIFT(65),
  [39] = {.count = 1, .reusable = false}, SHIFT(64),
  [41] = {.count = 1, .reusable = false}, SHIFT(82),
  [43] = {.count = 1, .reusable = false}, SHIFT(124),
  [45] = {.count = 1, .reusable = false}, SHIFT(100),
  [47] = {.count = 1, .reusable = false}, SHIFT(106),
  [49] = {.count = 1, .reusable = false}, SHIFT(119),
  [51] = {.count = 1, .reusable = true}, SHIFT(3),
  [53] = {.count = 1, .reusable = true}, SHIFT(108),
  [55] = {.count = 1, .reusable = true}, SHIFT(72),
  [57] = {.count = 1, .reusable = true}, SHIFT(123),
  [59] = {.count = 1, .reusable = true}, SHIFT(65),
  [61] = {.count = 1, .reusable = true}, SHIFT(64),
  [63] = {.count = 1, .reusable = true}, SHIFT(82),
  [65] = {.count = 1, .reusable = true}, SHIFT(105),
  [67] = {.count = 1, .reusable = true}, SHIFT(118),
  [69] = {.count = 1, .reusable = true}, SHIFT(106),
  [71] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 1),
  [73] = {.count = 1, .reusable = true}, SHIFT(2),
  [75] = {.count = 1, .reusable = true}, SHIFT(74),
  [77] = {.count = 1, .reusable = true}, SHIFT(121),
  [79] = {.count = 1, .reusable = true}, SHIFT(73),
  [81] = {.count = 1, .reusable = true}, SHIFT(70),
  [83] = {.count = 1, .reusable = true}, SHIFT(91),
  [85] = {.count = 1, .reusable = true}, SHIFT(98),
  [87] = {.count = 1, .reusable = true}, SHIFT(112),
  [89] = {.count = 1, .reusable = true}, SHIFT(115),
  [91] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 3),
  [93] = {.count = 1, .reusable = true}, SHIFT(119),
  [95] = {.count = 1, .reusable = true}, SHIFT(114),
  [97] = {.count = 1, .reusable = true}, SHIFT(113),
  [99] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 2),
  [101] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 4),
  [103] = {.count = 1, .reusable = true}, SHIFT(26),
  [105] = {.count = 1, .reusable = false}, REDUCE(sym__sp, 1),
  [107] = {.count = 1, .reusable = true}, REDUCE(aux_sym__sp_repeat1, 2),
  [109] = {.count = 2, .reusable = true}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(25),
  [112] = {.count = 1, .reusable = false}, REDUCE(aux_sym__sp_repeat1, 2),
  [114] = {.count = 2, .reusable = false}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(120),
  [117] = {.count = 2, .reusable = true}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(26),
  [120] = {.count = 2, .reusable = false}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(122),
  [123] = {.count = 1, .reusable = true}, REDUCE(sym__sp, 1),
  [125] = {.count = 1, .reusable = true}, SHIFT(25),
  [127] = {.count = 1, .reusable = true}, REDUCE(sym__comment_contents, 3),
  [129] = {.count = 1, .reusable = false}, REDUCE(sym__comment_contents, 3),
  [131] = {.count = 1, .reusable = true}, REDUCE(sym__comment_contents, 2),
  [133] = {.count = 1, .reusable = false}, REDUCE(sym__comment_contents, 2),
  [135] = {.count = 1, .reusable = true}, REDUCE(sym_tag, 3),
  [137] = {.count = 1, .reusable = false}, REDUCE(sym_tag, 3),
  [139] = {.count = 1, .reusable = true}, REDUCE(sym_comment, 2),
  [141] = {.count = 1, .reusable = false}, REDUCE(sym_comment, 2),
  [143] = {.count = 1, .reusable = false}, SHIFT(108),
  [145] = {.count = 1, .reusable = false}, SHIFT(118),
  [147] = {.count = 1, .reusable = true}, REDUCE(sym_str, 3),
  [149] = {.count = 1, .reusable = false}, REDUCE(sym_str, 3),
  [151] = {.count = 1, .reusable = false}, REDUCE(sym_escape_char, 1),
  [153] = {.count = 1, .reusable = true}, REDUCE(sym_str, 2),
  [155] = {.count = 1, .reusable = false}, REDUCE(sym_str, 2),
  [157] = {.count = 1, .reusable = false}, SHIFT(114),
  [159] = {.count = 1, .reusable = false}, SHIFT(115),
  [161] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(24),
  [164] = {.count = 1, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2),
  [166] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(122),
  [169] = {.count = 1, .reusable = false}, SHIFT(98),
  [171] = {.count = 1, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2),
  [173] = {.count = 1, .reusable = false}, SHIFT(112),
  [175] = {.count = 1, .reusable = false}, SHIFT(97),
  [177] = {.count = 1, .reusable = false}, SHIFT(52),
  [179] = {.count = 1, .reusable = false}, SHIFT(66),
  [181] = {.count = 1, .reusable = false}, SHIFT(49),
  [183] = {.count = 1, .reusable = false}, SHIFT(96),
  [185] = {.count = 1, .reusable = false}, SHIFT(68),
  [187] = {.count = 1, .reusable = true}, REDUCE(aux_sym__int_repeat1, 2),
  [189] = {.count = 1, .reusable = false}, REDUCE(aux_sym__int_repeat1, 2),
  [191] = {.count = 2, .reusable = false}, REDUCE(aux_sym__int_repeat1, 2), SHIFT_REPEAT(63),
  [194] = {.count = 1, .reusable = false}, SHIFT(50),
  [196] = {.count = 1, .reusable = false}, SHIFT(61),
  [198] = {.count = 1, .reusable = false}, SHIFT(46),
  [200] = {.count = 1, .reusable = false}, SHIFT(62),
  [202] = {.count = 2, .reusable = false}, REDUCE(aux_sym_str_repeat2, 2), SHIFT_REPEAT(97),
  [205] = {.count = 2, .reusable = false}, REDUCE(aux_sym_str_repeat2, 2), SHIFT_REPEAT(66),
  [208] = {.count = 1, .reusable = true}, REDUCE(sym_sym, 1),
  [210] = {.count = 1, .reusable = false}, REDUCE(sym_sym, 1),
  [212] = {.count = 1, .reusable = false}, SHIFT(75),
  [214] = {.count = 2, .reusable = false}, REDUCE(aux_sym_str_repeat1, 2), SHIFT_REPEAT(96),
  [217] = {.count = 2, .reusable = false}, REDUCE(aux_sym_str_repeat1, 2), SHIFT_REPEAT(68),
  [220] = {.count = 1, .reusable = true}, REDUCE(aux_sym_sym_repeat1, 2),
  [222] = {.count = 1, .reusable = false}, REDUCE(aux_sym_sym_repeat1, 2),
  [224] = {.count = 2, .reusable = false}, REDUCE(aux_sym_sym_repeat1, 2), SHIFT_REPEAT(69),
  [227] = {.count = 1, .reusable = false}, SHIFT(39),
  [229] = {.count = 1, .reusable = false}, SHIFT(77),
  [231] = {.count = 1, .reusable = true}, REDUCE(sym_sym, 2),
  [233] = {.count = 1, .reusable = false}, REDUCE(sym_sym, 2),
  [235] = {.count = 1, .reusable = false}, SHIFT(69),
  [237] = {.count = 1, .reusable = true}, REDUCE(sym__int, 1),
  [239] = {.count = 1, .reusable = false}, REDUCE(sym__int, 1),
  [241] = {.count = 1, .reusable = false}, SHIFT(63),
  [243] = {.count = 1, .reusable = false}, SHIFT(89),
  [245] = {.count = 1, .reusable = false}, SHIFT(57),
  [247] = {.count = 1, .reusable = false}, SHIFT(78),
  [249] = {.count = 1, .reusable = false}, SHIFT(76),
  [251] = {.count = 1, .reusable = false}, SHIFT(85),
  [253] = {.count = 1, .reusable = false}, SHIFT(79),
  [255] = {.count = 2, .reusable = false}, REDUCE(aux_sym__int_repeat1, 2), SHIFT_REPEAT(76),
  [258] = {.count = 1, .reusable = false}, SHIFT(38),
  [260] = {.count = 1, .reusable = false}, SHIFT(51),
  [262] = {.count = 2, .reusable = false}, REDUCE(aux_sym_sym_repeat1, 2), SHIFT_REPEAT(79),
  [265] = {.count = 1, .reusable = false}, SHIFT(71),
  [267] = {.count = 1, .reusable = true}, REDUCE(sym__float, 3),
  [269] = {.count = 1, .reusable = false}, REDUCE(sym__float, 3),
  [271] = {.count = 1, .reusable = false}, SHIFT(84),
  [273] = {.count = 1, .reusable = false}, SHIFT(92),
  [275] = {.count = 1, .reusable = false}, SHIFT(101),
  [277] = {.count = 1, .reusable = false}, SHIFT(83),
  [279] = {.count = 1, .reusable = false}, SHIFT(117),
  [281] = {.count = 1, .reusable = true}, REDUCE(sym__float, 2),
  [283] = {.count = 1, .reusable = false}, REDUCE(sym__float, 2),
  [285] = {.count = 1, .reusable = false}, SHIFT(81),
  [287] = {.count = 1, .reusable = false}, SHIFT(34),
  [289] = {.count = 1, .reusable = false}, SHIFT(28),
  [291] = {.count = 1, .reusable = false}, SHIFT(87),
  [293] = {.count = 2, .reusable = false}, REDUCE(aux_sym__comment_contents_repeat1, 2), SHIFT_REPEAT(84),
  [296] = {.count = 2, .reusable = false}, REDUCE(aux_sym__comment_contents_repeat1, 2), SHIFT_REPEAT(92),
  [299] = {.count = 1, .reusable = false}, REDUCE(aux_sym__comment_contents_repeat1, 2),
  [301] = {.count = 1, .reusable = false}, SHIFT(88),
  [303] = {.count = 1, .reusable = false}, SHIFT(31),
  [305] = {.count = 1, .reusable = false}, SHIFT(86),
  [307] = {.count = 1, .reusable = false}, SHIFT(29),
  [309] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 4),
  [311] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 4),
  [313] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 2),
  [315] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 2),
  [317] = {.count = 1, .reusable = true}, REDUCE(sym_num, 1),
  [319] = {.count = 1, .reusable = false}, REDUCE(sym_num, 1),
  [321] = {.count = 1, .reusable = true}, REDUCE(sym_num, 2),
  [323] = {.count = 1, .reusable = false}, REDUCE(sym_num, 2),
  [325] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 7),
  [327] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 7),
  [329] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 3),
  [331] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 3),
  [333] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 6),
  [335] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 6),
  [337] = {.count = 2, .reusable = true}, REDUCE(aux_sym__int_repeat1, 2), SHIFT_REPEAT(110),
  [340] = {.count = 1, .reusable = true}, SHIFT(110),
  [342] = {.count = 1, .reusable = true}, SHIFT(30),
  [344] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 5),
  [346] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 5),
  [348] = {.count = 1, .reusable = true}, SHIFT(94),
  [350] = {.count = 1, .reusable = true}, SHIFT(95),
  [352] = {.count = 1, .reusable = true}, SHIFT(93),
  [354] = {.count = 1, .reusable = true}, SHIFT(90),
  [356] = {.count = 1, .reusable = true}, SHIFT(111),
  [358] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_alv(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
