#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  sym__wc = 1,
  anon_sym_LPAREN = 2,
  aux_sym__comment_contents_token1 = 3,
  anon_sym_RPAREN = 4,
  anon_sym_POUND = 5,
  sym__first = 6,
  sym__digit = 7,
  anon_sym_DOT = 8,
  sym_escape_char = 9,
  anon_sym_DASH = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_str_token1 = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_str_token2 = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym_source_file = 17,
  sym__sp = 18,
  sym__comment_contents = 19,
  sym_comment = 20,
  sym__int = 21,
  sym__float = 22,
  sym_sym = 23,
  sym_num = 24,
  sym_str = 25,
  sym__atom = 26,
  sym__expression = 27,
  sym_tag = 28,
  sym_head = 29,
  sym_cell = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym__sp_repeat1 = 32,
  aux_sym__comment_contents_repeat1 = 33,
  aux_sym__int_repeat1 = 34,
  aux_sym_sym_repeat1 = 35,
  aux_sym_str_repeat1 = 36,
  aux_sym_str_repeat2 = 37,
  aux_sym_cell_repeat1 = 38,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__wc] = "_wc",
  [anon_sym_LPAREN] = "(",
  [aux_sym__comment_contents_token1] = "_comment_contents_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_POUND] = "#",
  [sym__first] = "_first",
  [sym__digit] = "_digit",
  [anon_sym_DOT] = ".",
  [sym_escape_char] = "escape_char",
  [anon_sym_DASH] = "-",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_str_token1] = "str_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_str_token2] = "str_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__sp] = "_sp",
  [sym__comment_contents] = "_comment_contents",
  [sym_comment] = "comment",
  [sym__int] = "_int",
  [sym__float] = "_float",
  [sym_sym] = "sym",
  [sym_num] = "num",
  [sym_str] = "str",
  [sym__atom] = "_atom",
  [sym__expression] = "_expression",
  [sym_tag] = "tag",
  [sym_head] = "head",
  [sym_cell] = "cell",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__sp_repeat1] = "_sp_repeat1",
  [aux_sym__comment_contents_repeat1] = "_comment_contents_repeat1",
  [aux_sym__int_repeat1] = "_int_repeat1",
  [aux_sym_sym_repeat1] = "sym_repeat1",
  [aux_sym_str_repeat1] = "str_repeat1",
  [aux_sym_str_repeat2] = "str_repeat2",
  [aux_sym_cell_repeat1] = "cell_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__wc] = sym__wc,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym__comment_contents_token1] = aux_sym__comment_contents_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym__first] = sym__first,
  [sym__digit] = sym__digit,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_escape_char] = sym_escape_char,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_str_token1] = aux_sym_str_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_str_token2] = aux_sym_str_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__sp] = sym__sp,
  [sym__comment_contents] = sym__comment_contents,
  [sym_comment] = sym_comment,
  [sym__int] = sym__int,
  [sym__float] = sym__float,
  [sym_sym] = sym_sym,
  [sym_num] = sym_num,
  [sym_str] = sym_str,
  [sym__atom] = sym__atom,
  [sym__expression] = sym__expression,
  [sym_tag] = sym_tag,
  [sym_head] = sym_head,
  [sym_cell] = sym_cell,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__sp_repeat1] = aux_sym__sp_repeat1,
  [aux_sym__comment_contents_repeat1] = aux_sym__comment_contents_repeat1,
  [aux_sym__int_repeat1] = aux_sym__int_repeat1,
  [aux_sym_sym_repeat1] = aux_sym_sym_repeat1,
  [aux_sym_str_repeat1] = aux_sym_str_repeat1,
  [aux_sym_str_repeat2] = aux_sym_str_repeat2,
  [aux_sym_cell_repeat1] = aux_sym_cell_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__wc] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__comment_contents_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym__first] = {
    .visible = false,
    .named = true,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_str_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_str_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sp] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_contents] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym_sym] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_head] = {
    .visible = true,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sp_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_contents_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__int_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sym_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_str_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == '=' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(17);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__wc);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__comment_contents_token1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__comment_contents_token1);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(10);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__first);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__digit);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_escape_char);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_str_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_str_token1);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_str_token1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(17);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_str_token2);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_str_token2);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_str_token2);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\') ADVANCE(17);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym__first] = ACTIONS(1),
    [sym__digit] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_escape_char] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(77),
    [sym__sp] = STATE(7),
    [sym_comment] = STATE(18),
    [sym__int] = STATE(60),
    [sym__float] = STATE(60),
    [sym_sym] = STATE(50),
    [sym_num] = STATE(50),
    [sym_str] = STATE(50),
    [sym__atom] = STATE(50),
    [sym__expression] = STATE(50),
    [sym_cell] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym__sp_repeat1] = STATE(18),
    [aux_sym__int_repeat1] = STATE(37),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__wc] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [sym__first] = ACTIONS(11),
    [sym__digit] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
  },
  [2] = {
    [sym__sp] = STATE(9),
    [sym_comment] = STATE(17),
    [sym__int] = STATE(60),
    [sym__float] = STATE(60),
    [sym_sym] = STATE(59),
    [sym_num] = STATE(59),
    [sym_str] = STATE(59),
    [sym__atom] = STATE(59),
    [sym__expression] = STATE(59),
    [sym_tag] = STATE(3),
    [sym_head] = STATE(33),
    [sym_cell] = STATE(59),
    [aux_sym__sp_repeat1] = STATE(17),
    [aux_sym__int_repeat1] = STATE(37),
    [sym__wc] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(27),
    [sym__first] = ACTIONS(11),
    [sym__digit] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(29),
  },
  [3] = {
    [sym__sp] = STATE(4),
    [sym_comment] = STATE(17),
    [sym__int] = STATE(60),
    [sym__float] = STATE(60),
    [sym_sym] = STATE(59),
    [sym_num] = STATE(59),
    [sym_str] = STATE(59),
    [sym__atom] = STATE(59),
    [sym__expression] = STATE(59),
    [sym_head] = STATE(27),
    [sym_cell] = STATE(59),
    [aux_sym__sp_repeat1] = STATE(17),
    [aux_sym__int_repeat1] = STATE(37),
    [sym__wc] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(27),
    [sym__first] = ACTIONS(11),
    [sym__digit] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    STATE(28), 1,
      sym_head,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(59), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [43] = 12,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(50), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [86] = 12,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      sym__first,
    ACTIONS(57), 1,
      sym__digit,
    ACTIONS(60), 1,
      anon_sym_DOT,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(50), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [129] = 12,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_source_file_repeat1,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(50), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [172] = 12,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(50), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [215] = 12,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_head,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(59), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [258] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(63), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [298] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(63), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [338] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(63), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [378] = 11,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(63), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [418] = 10,
    ACTIONS(11), 1,
      sym__first,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(60), 2,
      sym__int,
      sym__float,
    STATE(63), 6,
      sym_sym,
      sym_num,
      sym_str,
      sym__atom,
      sym__expression,
      sym_cell,
  [455] = 5,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      sym__wc,
    ACTIONS(89), 1,
      anon_sym_POUND,
    STATE(15), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(87), 7,
      anon_sym_LPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [478] = 4,
    ACTIONS(92), 1,
      sym__wc,
    ACTIONS(95), 1,
      anon_sym_POUND,
    STATE(16), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(87), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [499] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(98), 1,
      sym__wc,
    STATE(16), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(100), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [520] = 5,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      sym__wc,
    STATE(15), 2,
      sym_comment,
      aux_sym__sp_repeat1,
    ACTIONS(100), 7,
      anon_sym_LPAREN,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [543] = 2,
    ACTIONS(106), 1,
      sym__wc,
    ACTIONS(108), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [558] = 2,
    ACTIONS(110), 1,
      sym__wc,
    ACTIONS(112), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [573] = 2,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(116), 8,
      anon_sym_LPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [588] = 2,
    ACTIONS(118), 1,
      sym__wc,
    ACTIONS(120), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [603] = 2,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(108), 8,
      anon_sym_LPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [618] = 2,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      sym__wc,
    ACTIONS(120), 8,
      anon_sym_LPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [633] = 2,
    ACTIONS(114), 1,
      sym__wc,
    ACTIONS(116), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_POUND,
      sym__first,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [648] = 2,
    ACTIONS(122), 1,
      sym__first,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym__digit,
      anon_sym_DOT,
      anon_sym_DASH,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [661] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym__sp,
    STATE(31), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [681] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(11), 1,
      sym__sp,
    STATE(29), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [701] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym__sp,
    STATE(30), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [721] = 6,
    ACTIONS(130), 1,
      sym__wc,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      anon_sym_POUND,
    STATE(14), 1,
      sym__sp,
    STATE(30), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [741] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(11), 1,
      sym__sp,
    STATE(30), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [761] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym__sp,
    STATE(30), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [781] = 6,
    ACTIONS(23), 1,
      sym__wc,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym__sp,
    STATE(32), 1,
      aux_sym_cell_repeat1,
    STATE(17), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [801] = 4,
    ACTIONS(138), 1,
      sym__wc,
    STATE(34), 1,
      aux_sym_sym_repeat1,
    ACTIONS(140), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(142), 2,
      sym__first,
      sym__digit,
  [816] = 4,
    ACTIONS(145), 1,
      sym__wc,
    ACTIONS(149), 1,
      sym__digit,
    STATE(35), 1,
      aux_sym__int_repeat1,
    ACTIONS(147), 3,
      anon_sym_RPAREN,
      anon_sym_POUND,
      anon_sym_DOT,
  [831] = 4,
    ACTIONS(152), 1,
      sym__wc,
    STATE(38), 1,
      aux_sym_sym_repeat1,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(156), 2,
      sym__first,
      sym__digit,
  [846] = 5,
    ACTIONS(158), 1,
      sym__wc,
    ACTIONS(162), 1,
      sym__digit,
    ACTIONS(164), 1,
      anon_sym_DOT,
    STATE(35), 1,
      aux_sym__int_repeat1,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [863] = 4,
    ACTIONS(166), 1,
      sym__wc,
    STATE(34), 1,
      aux_sym_sym_repeat1,
    ACTIONS(168), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
    ACTIONS(170), 2,
      sym__first,
      sym__digit,
  [878] = 4,
    ACTIONS(37), 1,
      sym__digit,
    ACTIONS(39), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym__int_repeat1,
    STATE(58), 2,
      sym__int,
      sym__float,
  [892] = 4,
    ACTIONS(172), 1,
      anon_sym_LPAREN,
    ACTIONS(175), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [906] = 4,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
    ACTIONS(182), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [920] = 4,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
    ACTIONS(182), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [934] = 4,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
    ACTIONS(188), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(41), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [948] = 4,
    ACTIONS(162), 1,
      sym__digit,
    ACTIONS(192), 1,
      sym__wc,
    STATE(35), 1,
      aux_sym__int_repeat1,
    ACTIONS(194), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [962] = 4,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
    ACTIONS(182), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    STATE(40), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [976] = 4,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
    ACTIONS(198), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(45), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [990] = 4,
    ACTIONS(202), 1,
      sym__wc,
    ACTIONS(206), 1,
      sym__digit,
    STATE(44), 1,
      aux_sym__int_repeat1,
    ACTIONS(204), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1004] = 4,
    ACTIONS(162), 1,
      sym__digit,
    ACTIONS(202), 1,
      sym__wc,
    STATE(35), 1,
      aux_sym__int_repeat1,
    ACTIONS(204), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1018] = 4,
    ACTIONS(180), 1,
      anon_sym_LPAREN,
    ACTIONS(208), 1,
      aux_sym__comment_contents_token1,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(42), 2,
      sym__comment_contents,
      aux_sym__comment_contents_repeat1,
  [1032] = 4,
    ACTIONS(5), 1,
      sym__wc,
    ACTIONS(9), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym__sp,
    STATE(18), 2,
      sym_comment,
      aux_sym__sp_repeat1,
  [1046] = 3,
    ACTIONS(214), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym_str_repeat2,
    ACTIONS(212), 2,
      sym_escape_char,
      aux_sym_str_token2,
  [1057] = 3,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      aux_sym_str_repeat1,
    ACTIONS(216), 2,
      sym_escape_char,
      aux_sym_str_token1,
  [1068] = 3,
    ACTIONS(221), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      aux_sym_str_repeat1,
    ACTIONS(218), 2,
      sym_escape_char,
      aux_sym_str_token1,
  [1079] = 3,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym_str_repeat2,
    ACTIONS(223), 2,
      sym_escape_char,
      aux_sym_str_token2,
  [1090] = 3,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_str_repeat1,
    ACTIONS(228), 2,
      sym_escape_char,
      aux_sym_str_token1,
  [1101] = 3,
    ACTIONS(230), 1,
      anon_sym_SQUOTE,
    STATE(51), 1,
      aux_sym_str_repeat2,
    ACTIONS(232), 2,
      sym_escape_char,
      aux_sym_str_token2,
  [1112] = 2,
    ACTIONS(234), 1,
      sym__wc,
    ACTIONS(236), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1120] = 2,
    ACTIONS(238), 1,
      sym__wc,
    ACTIONS(240), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1128] = 2,
    ACTIONS(242), 1,
      sym__wc,
    ACTIONS(244), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1136] = 2,
    ACTIONS(246), 1,
      sym__wc,
    ACTIONS(248), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1144] = 2,
    ACTIONS(250), 1,
      sym__wc,
    ACTIONS(252), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1152] = 2,
    ACTIONS(254), 1,
      sym__wc,
    ACTIONS(256), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1160] = 2,
    ACTIONS(258), 1,
      sym__wc,
    ACTIONS(133), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1168] = 3,
    ACTIONS(260), 1,
      sym__digit,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym__int_repeat1,
  [1178] = 2,
    ACTIONS(264), 1,
      sym__wc,
    ACTIONS(266), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1186] = 3,
    ACTIONS(145), 1,
      anon_sym_RBRACK,
    ACTIONS(268), 1,
      sym__digit,
    STATE(66), 1,
      aux_sym__int_repeat1,
  [1196] = 2,
    ACTIONS(271), 1,
      sym__wc,
    ACTIONS(273), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1204] = 1,
    ACTIONS(116), 3,
      anon_sym_LPAREN,
      aux_sym__comment_contents_token1,
      anon_sym_RPAREN,
  [1210] = 1,
    ACTIONS(120), 3,
      anon_sym_LPAREN,
      aux_sym__comment_contents_token1,
      anon_sym_RPAREN,
  [1216] = 2,
    ACTIONS(275), 1,
      sym__wc,
    ACTIONS(277), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1224] = 2,
    ACTIONS(279), 1,
      sym__wc,
    ACTIONS(281), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1232] = 2,
    ACTIONS(283), 1,
      sym__wc,
    ACTIONS(285), 2,
      anon_sym_RPAREN,
      anon_sym_POUND,
  [1240] = 2,
    ACTIONS(287), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym__comment_contents,
  [1247] = 2,
    ACTIONS(289), 1,
      sym__digit,
    STATE(48), 1,
      aux_sym__int_repeat1,
  [1254] = 2,
    ACTIONS(291), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym__comment_contents,
  [1261] = 2,
    ACTIONS(293), 1,
      sym__digit,
    STATE(64), 1,
      aux_sym__int_repeat1,
  [1268] = 1,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 43,
  [SMALL_STATE(6)] = 86,
  [SMALL_STATE(7)] = 129,
  [SMALL_STATE(8)] = 172,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 258,
  [SMALL_STATE(11)] = 298,
  [SMALL_STATE(12)] = 338,
  [SMALL_STATE(13)] = 378,
  [SMALL_STATE(14)] = 418,
  [SMALL_STATE(15)] = 455,
  [SMALL_STATE(16)] = 478,
  [SMALL_STATE(17)] = 499,
  [SMALL_STATE(18)] = 520,
  [SMALL_STATE(19)] = 543,
  [SMALL_STATE(20)] = 558,
  [SMALL_STATE(21)] = 573,
  [SMALL_STATE(22)] = 588,
  [SMALL_STATE(23)] = 603,
  [SMALL_STATE(24)] = 618,
  [SMALL_STATE(25)] = 633,
  [SMALL_STATE(26)] = 648,
  [SMALL_STATE(27)] = 661,
  [SMALL_STATE(28)] = 681,
  [SMALL_STATE(29)] = 701,
  [SMALL_STATE(30)] = 721,
  [SMALL_STATE(31)] = 741,
  [SMALL_STATE(32)] = 761,
  [SMALL_STATE(33)] = 781,
  [SMALL_STATE(34)] = 801,
  [SMALL_STATE(35)] = 816,
  [SMALL_STATE(36)] = 831,
  [SMALL_STATE(37)] = 846,
  [SMALL_STATE(38)] = 863,
  [SMALL_STATE(39)] = 878,
  [SMALL_STATE(40)] = 892,
  [SMALL_STATE(41)] = 906,
  [SMALL_STATE(42)] = 920,
  [SMALL_STATE(43)] = 934,
  [SMALL_STATE(44)] = 948,
  [SMALL_STATE(45)] = 962,
  [SMALL_STATE(46)] = 976,
  [SMALL_STATE(47)] = 990,
  [SMALL_STATE(48)] = 1004,
  [SMALL_STATE(49)] = 1018,
  [SMALL_STATE(50)] = 1032,
  [SMALL_STATE(51)] = 1046,
  [SMALL_STATE(52)] = 1057,
  [SMALL_STATE(53)] = 1068,
  [SMALL_STATE(54)] = 1079,
  [SMALL_STATE(55)] = 1090,
  [SMALL_STATE(56)] = 1101,
  [SMALL_STATE(57)] = 1112,
  [SMALL_STATE(58)] = 1120,
  [SMALL_STATE(59)] = 1128,
  [SMALL_STATE(60)] = 1136,
  [SMALL_STATE(61)] = 1144,
  [SMALL_STATE(62)] = 1152,
  [SMALL_STATE(63)] = 1160,
  [SMALL_STATE(64)] = 1168,
  [SMALL_STATE(65)] = 1178,
  [SMALL_STATE(66)] = 1186,
  [SMALL_STATE(67)] = 1196,
  [SMALL_STATE(68)] = 1204,
  [SMALL_STATE(69)] = 1210,
  [SMALL_STATE(70)] = 1216,
  [SMALL_STATE(71)] = 1224,
  [SMALL_STATE(72)] = 1232,
  [SMALL_STATE(73)] = 1240,
  [SMALL_STATE(74)] = 1247,
  [SMALL_STATE(75)] = 1254,
  [SMALL_STATE(76)] = 1261,
  [SMALL_STATE(77)] = 1268,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 0),
  [5] = {.count = 1, .reusable = true}, SHIFT(18),
  [7] = {.count = 1, .reusable = false}, SHIFT(2),
  [9] = {.count = 1, .reusable = false}, SHIFT(73),
  [11] = {.count = 1, .reusable = false}, SHIFT(36),
  [13] = {.count = 1, .reusable = false}, SHIFT(37),
  [15] = {.count = 1, .reusable = false}, SHIFT(74),
  [17] = {.count = 1, .reusable = false}, SHIFT(39),
  [19] = {.count = 1, .reusable = false}, SHIFT(55),
  [21] = {.count = 1, .reusable = false}, SHIFT(56),
  [23] = {.count = 1, .reusable = true}, SHIFT(17),
  [25] = {.count = 1, .reusable = false}, SHIFT(70),
  [27] = {.count = 1, .reusable = false}, SHIFT(75),
  [29] = {.count = 1, .reusable = false}, SHIFT(76),
  [31] = {.count = 1, .reusable = false}, SHIFT(67),
  [33] = {.count = 1, .reusable = true}, SHIFT(2),
  [35] = {.count = 1, .reusable = true}, SHIFT(71),
  [37] = {.count = 1, .reusable = true}, SHIFT(37),
  [39] = {.count = 1, .reusable = true}, SHIFT(74),
  [41] = {.count = 1, .reusable = true}, SHIFT(39),
  [43] = {.count = 1, .reusable = true}, SHIFT(55),
  [45] = {.count = 1, .reusable = true}, SHIFT(56),
  [47] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 2),
  [49] = {.count = 1, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2),
  [51] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [54] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [57] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [60] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [63] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [66] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [69] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [72] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 1),
  [74] = {.count = 1, .reusable = true}, SHIFT(67),
  [76] = {.count = 1, .reusable = true}, SHIFT(62),
  [78] = {.count = 1, .reusable = true}, SHIFT(61),
  [80] = {.count = 1, .reusable = true}, SHIFT(57),
  [82] = {.count = 1, .reusable = true}, REDUCE(aux_sym__sp_repeat1, 2),
  [84] = {.count = 2, .reusable = true}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(15),
  [87] = {.count = 1, .reusable = false}, REDUCE(aux_sym__sp_repeat1, 2),
  [89] = {.count = 2, .reusable = false}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(73),
  [92] = {.count = 2, .reusable = true}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(16),
  [95] = {.count = 2, .reusable = false}, REDUCE(aux_sym__sp_repeat1, 2), SHIFT_REPEAT(75),
  [98] = {.count = 1, .reusable = true}, SHIFT(16),
  [100] = {.count = 1, .reusable = false}, REDUCE(sym__sp, 1),
  [102] = {.count = 1, .reusable = true}, REDUCE(sym__sp, 1),
  [104] = {.count = 1, .reusable = true}, SHIFT(15),
  [106] = {.count = 1, .reusable = true}, REDUCE(sym_comment, 2),
  [108] = {.count = 1, .reusable = false}, REDUCE(sym_comment, 2),
  [110] = {.count = 1, .reusable = true}, REDUCE(sym_tag, 3),
  [112] = {.count = 1, .reusable = false}, REDUCE(sym_tag, 3),
  [114] = {.count = 1, .reusable = true}, REDUCE(sym__comment_contents, 2),
  [116] = {.count = 1, .reusable = false}, REDUCE(sym__comment_contents, 2),
  [118] = {.count = 1, .reusable = true}, REDUCE(sym__comment_contents, 3),
  [120] = {.count = 1, .reusable = false}, REDUCE(sym__comment_contents, 3),
  [122] = {.count = 1, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2),
  [124] = {.count = 1, .reusable = false}, SHIFT(71),
  [126] = {.count = 1, .reusable = false}, SHIFT(57),
  [128] = {.count = 1, .reusable = false}, SHIFT(61),
  [130] = {.count = 2, .reusable = true}, REDUCE(aux_sym_cell_repeat1, 2), SHIFT_REPEAT(17),
  [133] = {.count = 1, .reusable = false}, REDUCE(aux_sym_cell_repeat1, 2),
  [135] = {.count = 2, .reusable = false}, REDUCE(aux_sym_cell_repeat1, 2), SHIFT_REPEAT(75),
  [138] = {.count = 1, .reusable = true}, REDUCE(aux_sym_sym_repeat1, 2),
  [140] = {.count = 1, .reusable = false}, REDUCE(aux_sym_sym_repeat1, 2),
  [142] = {.count = 2, .reusable = false}, REDUCE(aux_sym_sym_repeat1, 2), SHIFT_REPEAT(34),
  [145] = {.count = 1, .reusable = true}, REDUCE(aux_sym__int_repeat1, 2),
  [147] = {.count = 1, .reusable = false}, REDUCE(aux_sym__int_repeat1, 2),
  [149] = {.count = 2, .reusable = false}, REDUCE(aux_sym__int_repeat1, 2), SHIFT_REPEAT(35),
  [152] = {.count = 1, .reusable = true}, REDUCE(sym_sym, 1),
  [154] = {.count = 1, .reusable = false}, REDUCE(sym_sym, 1),
  [156] = {.count = 1, .reusable = false}, SHIFT(38),
  [158] = {.count = 1, .reusable = true}, REDUCE(sym__int, 1),
  [160] = {.count = 1, .reusable = false}, REDUCE(sym__int, 1),
  [162] = {.count = 1, .reusable = false}, SHIFT(35),
  [164] = {.count = 1, .reusable = false}, SHIFT(47),
  [166] = {.count = 1, .reusable = true}, REDUCE(sym_sym, 2),
  [168] = {.count = 1, .reusable = false}, REDUCE(sym_sym, 2),
  [170] = {.count = 1, .reusable = false}, SHIFT(34),
  [172] = {.count = 2, .reusable = false}, REDUCE(aux_sym__comment_contents_repeat1, 2), SHIFT_REPEAT(43),
  [175] = {.count = 2, .reusable = false}, REDUCE(aux_sym__comment_contents_repeat1, 2), SHIFT_REPEAT(40),
  [178] = {.count = 1, .reusable = false}, REDUCE(aux_sym__comment_contents_repeat1, 2),
  [180] = {.count = 1, .reusable = false}, SHIFT(43),
  [182] = {.count = 1, .reusable = false}, SHIFT(40),
  [184] = {.count = 1, .reusable = false}, SHIFT(69),
  [186] = {.count = 1, .reusable = false}, SHIFT(24),
  [188] = {.count = 1, .reusable = false}, SHIFT(41),
  [190] = {.count = 1, .reusable = false}, SHIFT(68),
  [192] = {.count = 1, .reusable = true}, REDUCE(sym__float, 3),
  [194] = {.count = 1, .reusable = false}, REDUCE(sym__float, 3),
  [196] = {.count = 1, .reusable = false}, SHIFT(22),
  [198] = {.count = 1, .reusable = false}, SHIFT(45),
  [200] = {.count = 1, .reusable = false}, SHIFT(25),
  [202] = {.count = 1, .reusable = true}, REDUCE(sym__float, 2),
  [204] = {.count = 1, .reusable = false}, REDUCE(sym__float, 2),
  [206] = {.count = 1, .reusable = false}, SHIFT(44),
  [208] = {.count = 1, .reusable = false}, SHIFT(42),
  [210] = {.count = 1, .reusable = false}, SHIFT(21),
  [212] = {.count = 1, .reusable = false}, SHIFT(54),
  [214] = {.count = 1, .reusable = false}, SHIFT(72),
  [216] = {.count = 1, .reusable = false}, SHIFT(53),
  [218] = {.count = 2, .reusable = false}, REDUCE(aux_sym_str_repeat1, 2), SHIFT_REPEAT(53),
  [221] = {.count = 1, .reusable = false}, REDUCE(aux_sym_str_repeat1, 2),
  [223] = {.count = 2, .reusable = false}, REDUCE(aux_sym_str_repeat2, 2), SHIFT_REPEAT(54),
  [226] = {.count = 1, .reusable = false}, REDUCE(aux_sym_str_repeat2, 2),
  [228] = {.count = 1, .reusable = false}, SHIFT(52),
  [230] = {.count = 1, .reusable = false}, SHIFT(65),
  [232] = {.count = 1, .reusable = false}, SHIFT(51),
  [234] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 5),
  [236] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 5),
  [238] = {.count = 1, .reusable = true}, REDUCE(sym_num, 2),
  [240] = {.count = 1, .reusable = false}, REDUCE(sym_num, 2),
  [242] = {.count = 1, .reusable = true}, REDUCE(sym_head, 1),
  [244] = {.count = 1, .reusable = false}, REDUCE(sym_head, 1),
  [246] = {.count = 1, .reusable = true}, REDUCE(sym_num, 1),
  [248] = {.count = 1, .reusable = false}, REDUCE(sym_num, 1),
  [250] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 6),
  [252] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 6),
  [254] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 7),
  [256] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 7),
  [258] = {.count = 1, .reusable = true}, REDUCE(aux_sym_cell_repeat1, 2),
  [260] = {.count = 1, .reusable = true}, SHIFT(66),
  [262] = {.count = 1, .reusable = true}, SHIFT(20),
  [264] = {.count = 1, .reusable = true}, REDUCE(sym_str, 2),
  [266] = {.count = 1, .reusable = false}, REDUCE(sym_str, 2),
  [268] = {.count = 2, .reusable = true}, REDUCE(aux_sym__int_repeat1, 2), SHIFT_REPEAT(66),
  [271] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 3),
  [273] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 3),
  [275] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 2),
  [277] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 2),
  [279] = {.count = 1, .reusable = true}, REDUCE(sym_cell, 4),
  [281] = {.count = 1, .reusable = false}, REDUCE(sym_cell, 4),
  [283] = {.count = 1, .reusable = true}, REDUCE(sym_str, 3),
  [285] = {.count = 1, .reusable = false}, REDUCE(sym_str, 3),
  [287] = {.count = 1, .reusable = true}, SHIFT(49),
  [289] = {.count = 1, .reusable = true}, SHIFT(48),
  [291] = {.count = 1, .reusable = true}, SHIFT(46),
  [293] = {.count = 1, .reusable = true}, SHIFT(64),
  [295] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_alv(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
